Clarify Terraform 1.3 requirement (fixes #88)
Azure/terraform-azurerm-network pull request #89
Opened 2023-01-16 05:07 UTC by don-code

# Describe your changes

This change fixes #88 - it being unclear which version of Terraform is required to use the module - by explicitly qualifying that 1.3 or higher is required.

## Issue number

#88

## Checklist before requesting a review
- [x] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [x] I have executed pre-commit on my machine
- [x] I have passed pr-check on my machine

Thanks for your cooperation!

2023-01-16 05:09 UTC, don-code commented
@microsoft-github-policy-service agree

2023-01-17 01:41 UTC, lonegunmanb commented
Thanks @don-code for opening this pr! Would you please upgrade the `versions.tf` file inside `example` folder too? Thanks!

https://github.com/Azure/terraform-azurerm-network/blob/d2971121d73b72110a8600a9bd1f543c0b45e365/examples/startup/versions.tf#L1-L3

2023-01-17 01:42 UTC, lonegunmanb requested changes
Thanks @don-code for opening this pr! Would you please upgrade the `versions.tf` file inside `example` folder too? Thanks!

https://github.com/Azure/terraform-azurerm-network/blob/d2971121d73b72110a8600a9bd1f543c0b45e365/examples/startup/versions.tf#L1-L3

2023-01-17 13:47 UTC, don-code commented
Yes, that's now changed as well.

2023-01-28 02:50 UTC, lonegunmanb approved these changes
Thanks @don-code, LGTM 🚀

2023-01-28 02:50 UTC, merged